import { describe,expect,it,vi } from 'vitest';
import { createDailyBackupCoordinator } from './daily-backup-coordinator';
function fixture(){let now=new Date('2026-10-03T15:59:50.000Z'),visible=true;const capture=vi.fn().mockResolvedValue(null),changed=vi.fn();const c=createDailyBackupCoordinator({now:()=>now,timeZone:()=> 'Asia/Shanghai',visible:()=>visible,capture,changed});return{c,capture,changed,time:(s:string)=>{now=new Date(s);},visible:(v:boolean)=>{visible=v;}};}
describe('daily backup scheduling',()=>{
 it('checks startup and local midnight once, using the previous calendar date',async()=>{const f=fixture();await f.c.check();await f.c.check();expect(f.capture.mock.calls).toEqual([['2026-10-02']]);f.time('2026-10-03T16:00:01.000Z');await f.c.check();expect(f.capture.mock.calls.at(-1)).toEqual(['2026-10-03']);});
 it('waits for foreground and captures one recoverable snapshot after missing several days',async()=>{const f=fixture();f.visible(false);await f.c.check();expect(f.capture).not.toHaveBeenCalled();f.time('2026-10-08T06:00:00.000Z');f.visible(true);await f.c.check();expect(f.capture.mock.calls).toEqual([['2026-10-07']]);});
 it('does not mark failed captures successful and retries later without an alert loop',async()=>{const f=fixture();f.capture.mockRejectedValueOnce(new Error('Quota'));await f.c.check();await f.c.check();expect(f.capture).toHaveBeenCalledTimes(1);f.time('2026-10-03T16:01:00.000Z');await f.c.check();expect(f.capture).toHaveBeenCalledTimes(2);expect(f.changed).toHaveBeenLastCalledWith(null);});
 it('guards concurrent requests and invalidates after an aggregate replacement',async()=>{const f=fixture();let finish!:()=>void;f.capture.mockImplementationOnce(()=>new Promise<void>(r=>{finish=r;}));const checking=f.c.check();await f.c.check();f.c.invalidate();finish();await checking;await f.c.check();expect(f.capture).toHaveBeenCalledTimes(2);f.c.stop();f.time('2026-10-05T00:00:00.000Z');await f.c.check();expect(f.capture).toHaveBeenCalledTimes(2);});
});
